In [6]:
import numpy as np

my_list = [1,2,3,4]

type(np.array(my_list))

arr = np.array(my_list)

arr

array([1, 2, 3, 4])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
#np.zeros(5)
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.random.randint(0,10)

np.random.randint(0,1000,(4,4))

array([[ 41, 162, 155, 307],
       [979, 380,  45, 498],
       [563, 113, 609, 654],
       [918, 695, 214, 880]])

In [73]:
np.random.seed(101)

arr =np.random.randint(0,100,10)

arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [81]:
np.random.seed(101)

arr =np.random.randint(0,100,10)

arr

arr.max()
arr.min()
arr.mean()
arr.argmax()
arr.argmin()
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [82]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [88]:
mat[2,2]
mat[0,:] #row
mat[:,0] #col
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])